#define PORT 9999
#define SERVER_IP "118.45.183.29"
#define SIMULATOR_PORT 12453
#define SIMULATOR_IP "118.45.183.32"

#define MAXPENDING 50
#define HEADER_SIZE 9
#define HEADER_IDX_MESSAGETYPE 0
#define HEADER_IDX_SEQUENCE 2
#define HEADER_IDX_PAYLOADLENGTH 3
#define HEADER_IDX_DEVICETYPE 5
#define HEADER_IDX_DEVICEID 6

#define UTCTIME_IDX_YEAR 0
#define UTCTIME_IDX_MONTH 2
#define UTCTIME_IDX_DAY 3
#define UTCTIME_IDX_HOUR 4
#define UTCTIME_IDX_MIN 5
#define UTCTIME_IDX_MSEC 6

#define POSITION_IDX_LAT 0
#define POSITION_IDX_LON 4
#define POSITION_IDX_ELEV 8

#define PAYLOAD_IDX_FULL_DEVICE_ID 0
#define PAYLOAD_IDX_KEY_CODE_LENGTH 6
#define PAYLOAD_IDX_KEY_CODE 8

#define PAYLOAD_IDX_MESSAGEID 8
#define PAYLOAD_IDX_JSONMESSAGELENGTH 10
#define PAYLOAD_IDX_JSONMESSAGE 12
#define PAYLOAD_IDX_ENCODEDMESSAGELENGTH 10
#define PAYLOAD_IDX_ENCODEDMESSAGE 12

#define PAYLOAD_IDX_LAT 8
#define PAYLOAD_IDX_LON 12
#define PAYLOAD_IDX_ELEV 16

#define PAYLOAD_IDX_SERVER_TX_J2735_TX_RESULT 20
#define PAYLOAD_IDX_SERVER_TX_J2735_PSID 21
#define PAYLOAD_IDX_SERVER_TX_J2735_CHANNEL 25
#define PAYLOAD_IDX_SERVER_TX_J2735_TIMESLOT 26
#define PAYLOAD_IDX_SERVER_TX_J2735_TX_POWER 27
#define PAYLOAD_IDX_SERVER_TX_J2735_TX_RATE 28
#define PAYLOAD_IDX_SERVER_TX_J2735_PRIORITY 29
#define PAYLOAD_IDX_SERVER_TX_J2735_DOT2 30
#define PAYLOAD_IDX_SERVER_TX_J2735_MESSAGE_ID 31
#define PAYLOAD_IDX_SERVER_TX_J2735_ENCODED_MESSAGE_LENGTH 33
#define PAYLOAD_IDX_SERVER_TX_J2735_ENCODED_MESSAGE 35

#define PAYLOAD_IDX_ACK_CODE 0
#define PAYLOAD_IDX_ACK_SERVICEFLAG 1

#define MESSAGEFRAME_UTCTIME_IDX_YEAR 9
#define MESSAGEFRAME_UTCTIME_IDX_MONTH 11
#define MESSAGEFRAME_UTCTIME_IDX_DAY 12
#define MESSAGEFRAME_UTCTIME_IDX_HOUR 13
#define MESSAGEFRAME_UTCTIME_IDX_MIN 14
#define MESSAGEFRAME_UTCTIME_IDX_MSEC 15

#define MESSAGEFRAME_POSITION_IDX_LAT 17
#define MESSAGEFRAME_POSITION_IDX_LON 21
#define MESSAGEFRAME_POSITION_IDX_ELEV 25

#define MESSAGEFRAME_PAYLOAD_IDX_MESSAGEID 17
#define MESSAGEFRAME_PAYLOAD_IDX_JSONMESSAGELENGTH 19
#define MESSAGEFRAME_PAYLOAD_IDX_JSONMESSAGE 21

#define MESSAGEFRAME_PAYLOAD_IDX_TX_RESULT 29
#define MESSAGEFRAME_PAYLOAD_IDX_PSID 30
#define MESSAGEFRAME_PAYLOAD_IDX_CHANNEL 32
#define MESSAGEFRAME_PAYLOAD_IDX_TX_POWER 33
#define MESSAGEFRAME_PAYLOAD_IDX_TX_RATE 34
#define MESSAGEFRAME_PAYLOAD_IDX_SERVER_TX_J2735_MESSAGE_ID 40
#define MESSAGEFRAME_PAYLOAD_IDX_SERVER_TX_J2735_ENCODED_MESSAGE_LENGTH 42
#define MESSAGEFRAME_PAYLOAD_IDX_SERVER_TX_J2735_ENCODED_MESSAGE 44

#define MESSAGEFRAME_PAYLOAD_IDX_ACK_CODE 9
#define MESSAGEFRAME_PAYLOAD_IDX_ACK_SERVICEFLAG 10

#define HEADER_SIZE_MESSAGETYPE 2
#define HEADER_SIZE_SEQUENCE 1
#define HEADER_SIZE_PAYLOADLENGTH 2
#define HEADER_SIZE_DEVICETYPE 1
#define HEADER_SIZE_DEVICEID 3

#define PAYLOAD_SIZE_UTCTIME 8

#define UTCTIME_SIZE_YEAR 2
#define UTCTIME_SIZE_MONTH 1
#define UTCTIME_SIZE_DAY 1
#define UTCTIME_SIZE_HOUR 1
#define UTCTIME_SIZE_MIN 1
#define UTCTIME_SIZE_MSEC 2

#define PAYLOAD_SIZE_MESSAGE_ID 2
#define PAYLOAD_SIZE_JSONMESSAGELENGTH 2

#define PAYLOAD_SIZE_SERVER_TX_WITHOUT_MSG 35
#define PAYLOAD_SIZE_SIMULATOR_TX_WITHOUT_MSG 12

#define PAYLOAD_SIZE_SERVER_OR_CLIENT_JSON_DATA_WITHOUT_MSG 12

#define PAYLOAD_SIZE_FULL_DEVICE_ID 6
#define PAYLOAD_SIZE_KEY_CODE_LENGTH 2
#define PAYLOAD_SIZE_KEY_CODE 4

#define MESSAGEFRAME_PAYLOAD_SIZE_SIGN 12
#define MESSAGEFRAME_SIZE_SIGN 21

#define MESSAGEFRAME_PAYLOAD_SIZE_ACK 3
#define MESSAGEFRAME_SIZE_ACK 12


#define PAYLOAD_SIZE_MESSAGE_ID_AND_JSON_MESSAGE_LENGTH 4
#define PAYLOAD_SIZE_MESSAGE_ID_AND_ENCODED_MESSAGE_LENGTH 4

#define MESSAGEFRAME_SIZE_SERVER_TX_WITHOUT_MSG 44
#define MESSAGEFRAME_SIZE_SIMULATOR_TX_WITHOUT_MSG 21
#define MESSAGEFRAME_SIZE_SERVER_OR_CLIENT_JSON_DATA_WITHOUT_MSG 21

#define PAYLOAD_SIZE_ACK 3

#define MESSAGE_ID_VALUE_MAP 18
#define MESSAGE_ID_VALUE_SPAT 19
#define MESSAGE_ID_VALUE_BSM 20
#define MESSAGE_ID_VALUE_PVD 26

#define MESSAGE_TYPE_SERVER_OR_SIMULATOR_SIGN 0x000a
#define MESSAGE_TYPE_SIMULATOR_TX_J2735_DATA 0x0101
#define MESSAGE_TYPE_SERVER_TX_J2735_DATA 0x0201
#define MESSAGE_TYPE_SERVER_OR_CLIENT_JSON_DATA 0x0401
#define MESSAGE_TYPE_SERVER_OR_SIMULATOR_SIGN_ACK 0x000b

#define DEVICE_TYPE_SIMULATOR 0xac
#define DEVICE_TYPE_SERVER 0xce
#define DEVICE_TYPE_CLIENT 0xcf

#define SIGNCODE_SIGN_SUCCESS 0x00
#define SIGNCODE_SIGN_FAILED_UNKNOWN 0x01
#define SIGNCODE_SIGN_FAILED_KEY_ERROR 0x02

const char* SIGN_CODE[3] = {"SIGN_SUCCESS", "SIGN_FAILED_UNKNOWN", "SIGN_FAILED_KEY_ERROR"};

#define SERVICEFLAG_SIMULATOR_TX_J2735_DATA 0x01
#define SERVICEFLAG_USER_TX_J2735_DATA 0x80

const uint8_t KeyCode[4] = {0x63, 0x65, 0x73, 0x74};

const char* MESSAGE_ID[4] = {"MAP", "SPAT", "BSM", "PVD"};

uint8_t DEVID[4] = {0x01, 0x02, 0x03} ;